#!/bin/sh
# Generate runtime JS config from container env vars.
# Served by nginx at /mohaa-cdn-config.js (from /tmp/).
# Injected into HTML via sub_filter before </head>.
cat > /tmp/mohaa-cdn-config.js <<EOF
window.MOHAA_CDN_URL='${CDN_URL:-/assets}';
EOF
echo "MOHAAjs: CDN_URL=${CDN_URL:-/assets} written to /tmp/mohaa-cdn-config.js"

# Generate nginx CDN proxy upstream config.
# Extracts scheme + host from CDN_URL so nginx can reverse-proxy requests
# from /cdn-proxy/* to the real CDN — avoiding browser CORS blocks.
CDN_RAW="${CDN_URL:-/assets}"
# Only generate proxy config for http(s) URLs; local /assets doesn't need it.
if echo "$CDN_RAW" | grep -qE '^https?://'; then
    # Extract host (strip scheme, strip trailing path)
    CDN_HOST=$(echo "$CDN_RAW" | sed -E 's|^https?://||; s|/.*||')
    # Extract scheme + host as base
    CDN_BASE=$(echo "$CDN_RAW" | sed -E 's|(https?://[^/]+).*|\1|')
    # Extract path suffix (everything after scheme://host), strip trailing slash
    CDN_PATH=$(echo "$CDN_RAW" | sed -E 's|^https?://[^/]+||; s|/$||')
    cat > /etc/nginx/conf.d/cdn-proxy-upstream.conf <<EOCFG
# Auto-generated by docker-entrypoint.sh — do not edit.
set \$cdn_host    "${CDN_HOST}";
set \$cdn_backend "${CDN_BASE}${CDN_PATH}/";
EOCFG
    echo "MOHAAjs: CDN proxy: /cdn-proxy/(.*) -> ${CDN_BASE}${CDN_PATH}/<path> (Host: ${CDN_HOST})"
else
    # Local assets — CDN proxy not needed; create a stub that returns 404.
    cat > /etc/nginx/conf.d/cdn-proxy-upstream.conf <<EOCFG
# CDN_URL is local (/assets) — proxy not applicable.
set \$cdn_host    "localhost";
set \$cdn_backend "http://127.0.0.1:9999/";
EOCFG
    echo "MOHAAjs: CDN_URL is local ($CDN_RAW) — cdn-proxy disabled"
fi

# Start the WebSocket-to-UDP relay in the background.
# It listens on port 12300; nginx proxies /relay → 127.0.0.1:12300.
if [ -f /srv/relay/mohaa_relay.js ]; then
    echo "MOHAAjs: Starting WebSocket relay on port 12300"
    node /srv/relay/mohaa_relay.js 12300 &
fi

# Delegate to the official nginx entrypoint.
exec /docker-entrypoint.sh "$@"
