#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="$REPO_ROOT/scripts/env.macos-cross.sh"

find_osxcross_root() {
    if [[ -n "${OSXCROSS_ROOT:-}" ]] && [[ -d "$OSXCROSS_ROOT" ]]; then
        echo "$OSXCROSS_ROOT"
        return 0
    fi

    local candidates=(
        "/opt/osxcross"
        "$HOME/osxcross"
        "$HOME/.local/osxcross"
        "/usr/local/osxcross"
        "/usr/lib/osxcross"
    )

    local c
    for c in "${candidates[@]}"; do
        if [[ -d "$c/target/bin" ]]; then
            echo "$c"
            return 0
        fi
    done

    return 1
}

ROOT="$(find_osxcross_root || true)"
if [[ -z "$ROOT" ]]; then
    echo "ERROR: Could not detect osxcross automatically." >&2
    echo "Set OSXCROSS_ROOT first, then rerun this script." >&2
    echo "Example: export OSXCROSS_ROOT=/opt/osxcross" >&2
    exit 1
fi

SDK_TAG="${OSXCROSS_SDK_TAG:-darwin16}"

cat > "$OUT_FILE" <<EOF
#!/usr/bin/env bash
# Generated by scripts/configure-macos-cross-env.sh
export OSXCROSS_ROOT="$ROOT"
export PATH="\$OSXCROSS_ROOT/target/bin:\$PATH"

# Optional override for godot-cpp/tools/macos.py (default is darwin16)
export OSXCROSS_SDK_TAG="$SDK_TAG"
EOF

chmod +x "$OUT_FILE"

echo "Wrote: $OUT_FILE"
echo "Use it with:"
echo "  source scripts/env.macos-cross.sh"
echo "Then build with:"
echo "  ./scripts/setup-macos-build.sh"
echo "  ./build.sh macos arch=x86_64 osxcross_sdk=\$OSXCROSS_SDK_TAG"
echo "  ./build.sh macos arch=arm64 osxcross_sdk=\$OSXCROSS_SDK_TAG"
